### ISSUE TITLE
docker discussion is missing

### ISSUE THREAD

**Issue by jaknz** [retronas/discussions#127]
This link is a 404 now; do you have a persistent place to discuss this? I'm very interested in making this happen, and things have changed in the past couple of years.

> **Please note:** All further docker discussion will be moved to our dist repo [here](https://github.com/danmons/retronas-dist/discussions/6) until the technical issues are resolved and a way forward is established. Then we will break the discussions up however they make sense.
> 
> _Originally posted by @sairuk in https://github.com/retronas/discussions/discussions/78#discussioncomment-2511485_

**Comment by sairuk** [comment]
No there isn't, but knock yourself out here if you like https://github.com/orgs/retronas/discussions/78 

I've added some notes to that thread this morning.
